// AUTO-GENERATED by Physics Compiler — DO NOT EDIT
// Model: Diode (AVX2 Backend)
// Layout Hash: 5ecfcf18bdcf0ede
// FMA: disabled (deterministic)

#include "physics_tensors.h"  // Tensor structs
#include <vector>
#include <cmath>
#include <algorithm>

#if defined(__AVX2__)
#include <immintrin.h>


// Lane-wise exp() fallback (use SVML _mm256_exp_pd if available)
inline __m256d _mm256_exp_pd_fallback(__m256d v) {
    alignas(32) double tmp[4];
    _mm256_store_pd(tmp, v);
    for (int k = 0; k < 4; ++k) tmp[k] = std::exp(tmp[k]);
    return _mm256_load_pd(tmp);
}


// Lane-wise log() fallback
inline __m256d _mm256_log_pd_fallback(__m256d v) {
    alignas(32) double tmp[4];
    _mm256_store_pd(tmp, v);
    for (int k = 0; k < 4; ++k) tmp[k] = std::log(tmp[k]);
    return _mm256_load_pd(tmp);
}


// Bitwise abs for f64 (clear sign bit)
inline __m256d _mm256_abs_pd(__m256d v) {
    const __m256i mask = _mm256_set1_epi64x(0x7FFFFFFFFFFFFFFF);
    return _mm256_castsi256_pd(_mm256_and_si256(_mm256_castpd_si256(v), mask));
}

void batchDiodePhysics_avx2(DiodeTensor& tensor, const std::vector<double>& voltages) {
    const size_t n = tensor.size();

    // Pre-broadcast constants
    const __m256d vc_1 = _mm256_set1_pd(1.0);
    const __m256d vc_30 = _mm256_set1_pd(30.0);

    size_t i = 0;
    // --- SIMD Loop: 4 devices per iteration ---
    for (; i + 3 < n; i += 4) {

        // Gather terminal voltages (manual gather)
        const double* __restrict__ v_ptr = voltages.data();
        const int v_size = (int)voltages.size();

        alignas(32) double _buf_a[4];
        for (int k = 0; k < 4; ++k) {
            int idx = tensor.node_a[i + k];
            _buf_a[k] = (idx > 0 && idx <= v_size) ? v_ptr[idx - 1] : 0.0;
        }
        __m256d v_v_a = _mm256_load_pd(_buf_a);

        alignas(32) double _buf_c[4];
        for (int k = 0; k < 4; ++k) {
            int idx = tensor.node_c[i + k];
            _buf_c[k] = (idx > 0 && idx <= v_size) ? v_ptr[idx - 1] : 0.0;
        }
        __m256d v_v_c = _mm256_load_pd(_buf_c);

        // Load parameters
        __m256d v_Is = _mm256_loadu_pd(&tensor.Is[i]);
        __m256d v_N = _mm256_loadu_pd(&tensor.N[i]);
        __m256d v_Vt = _mm256_loadu_pd(&tensor.Vt[i]);
        __m256d v_Rs = _mm256_loadu_pd(&tensor.Rs[i]);
        __m256d v_GMIN = _mm256_loadu_pd(&tensor.GMIN[i]);

        __m256d v_v_d = _mm256_sub_pd(v_v_a, v_v_c);
        _mm256_storeu_pd(&tensor.v_d[i], v_v_d);
        __m256d v_n_vt = _mm256_mul_pd(v_N, v_Vt);
        __m256d v_arg = _mm256_div_pd(v_v_d, v_n_vt);
        __m256d v_arg_clamped = _mm256_min_pd(v_arg, vc_30);
        __m256d v_exp_val = _mm256_exp_pd_fallback(v_arg_clamped);
        __m256d v_i_base = _mm256_mul_pd(_mm256_sub_pd(v_exp_val, vc_1), v_Is);
        __m256d v_g_base = _mm256_mul_pd(_mm256_div_pd(v_Is, v_n_vt), v_exp_val);
        __m256d v_delta = _mm256_max_pd(_mm256_setzero_pd(), _mm256_sub_pd(v_v_d, _mm256_mul_pd(vc_30, v_n_vt)));
        __m256d v_i_d = _mm256_add_pd(_mm256_mul_pd(v_delta, v_g_base), v_i_base);
        _mm256_storeu_pd(&tensor.i_d[i], v_i_d);
        __m256d v_g_d = _mm256_max_pd(v_GMIN, v_g_base);
        _mm256_storeu_pd(&tensor.g_d[i], v_g_d);
    }

    // --- Scalar Tail Loop ---
    for (; i < n; ++i) {
        int n_a = tensor.node_a[i];
        double v_a = (n_a > 0 && n_a <= (int)voltages.size()) ? voltages[n_a - 1] : 0.0;
        int n_c = tensor.node_c[i];
        double v_c = (n_c > 0 && n_c <= (int)voltages.size()) ? voltages[n_c - 1] : 0.0;
        double Is = tensor.Is[i];
        double N = tensor.N[i];
        double Vt = tensor.Vt[i];
        double Rs = tensor.Rs[i];
        double GMIN = tensor.GMIN[i];

        tensor.v_d[i] = (v_a - v_c);
        double v_d = tensor.v_d[i];
        double n_vt = (N * Vt);
        double arg = (v_d / n_vt);
        double arg_clamped = std::min(arg, 30.0);
        double exp_val = std::exp(arg_clamped);
        double i_base = ((exp_val - 1.0) * Is);
        double g_base = ((Is / n_vt) * exp_val);
        double delta = std::max(0.0, (v_d - (30.0 * n_vt)));
        tensor.i_d[i] = ((delta * g_base) + i_base);
        double i_d = tensor.i_d[i];
        tensor.g_d[i] = std::max(GMIN, g_base);
        double g_d = tensor.g_d[i];
    }
}

// ── MOSFET Level-1 (Shichman-Hodges) AVX2 Kernel ──
// Adapted from physics compiler output for MosfetTensor field names.
// Uses saturation-region equations with max() clamping.
// GMIN = 1e-12 (constant, not per-device).

void batchMosfetPhysics_avx2(MosfetTensor& tensor, const std::vector<double>& voltages) {
    const size_t n = tensor.size();
    const __m256d v_GMIN = _mm256_set1_pd(1e-12);

    size_t i = 0;
    // --- SIMD Loop: 4 devices per iteration ---
    for (; i + 3 < n; i += 4) {
        const double* __restrict__ v_ptr = voltages.data();
        const int v_size = (int)voltages.size();

        // Gather terminal voltages
        alignas(32) double _buf_d[4];
        for (int k = 0; k < 4; ++k) {
            int idx = tensor.drains[i + k];
            _buf_d[k] = (idx > 0 && idx <= v_size) ? v_ptr[idx - 1] : 0.0;
        }
        __m256d v_v_d = _mm256_load_pd(_buf_d);

        alignas(32) double _buf_g[4];
        for (int k = 0; k < 4; ++k) {
            int idx = tensor.gates[i + k];
            _buf_g[k] = (idx > 0 && idx <= v_size) ? v_ptr[idx - 1] : 0.0;
        }
        __m256d v_v_g = _mm256_load_pd(_buf_g);

        alignas(32) double _buf_s[4];
        for (int k = 0; k < 4; ++k) {
            int idx = tensor.sources[i + k];
            _buf_s[k] = (idx > 0 && idx <= v_size) ? v_ptr[idx - 1] : 0.0;
        }
        __m256d v_v_s = _mm256_load_pd(_buf_s);

        // Load parameters
        __m256d v_Kp = _mm256_loadu_pd(&tensor.Kp[i]);
        __m256d v_W = _mm256_loadu_pd(&tensor.W[i]);
        __m256d v_L = _mm256_loadu_pd(&tensor.L[i]);
        __m256d v_Vth = _mm256_loadu_pd(&tensor.Vth[i]);
        __m256d v_lambda = _mm256_loadu_pd(&tensor.lambda[i]);

        // vgs, vds
        __m256d vgs_val = _mm256_sub_pd(v_v_g, v_v_s);
        __m256d vds_val = _mm256_sub_pd(v_v_d, v_v_s);
        _mm256_storeu_pd(&tensor.vgs[i], vgs_val);
        _mm256_storeu_pd(&tensor.vds[i], vds_val);

        // beta = Kp * (W / L)
        __m256d v_beta = _mm256_mul_pd(_mm256_div_pd(v_W, v_L), v_Kp);
        // vov = vgs - Vth
        __m256d v_vov = _mm256_sub_pd(v_vgs, v_Vth);

        // Saturation: ids = 0.5 * beta * vov^2 * (1 + lambda * vds)
        __m256d v_half_beta = _mm256_mul_pd(_mm256_set1_pd(0.5), v_beta);
        __m256d v_vov2 = _mm256_mul_pd(v_vov, v_vov);
        __m256d v_clm = _mm256_add_pd(_mm256_set1_pd(1.0), _mm256_mul_pd(v_lambda, v_vds));
        __m256d v_ids_raw = _mm256_mul_pd(_mm256_mul_pd(v_half_beta, v_vov2), v_clm);

        // gm = beta * vov * (1 + lambda * vds)
        __m256d v_gm_raw = _mm256_mul_pd(_mm256_mul_pd(v_beta, v_vov), v_clm);

        // gds = 0.5 * beta * vov^2 * lambda
        __m256d v_gds_raw = _mm256_mul_pd(_mm256_mul_pd(v_half_beta, v_vov2), v_lambda);

        // Clamp: ids = max(0, ids), gm/gds = max(GMIN, ...)
        __m256d v_ids = _mm256_max_pd(_mm256_setzero_pd(), v_ids_raw);
        __m256d v_gm = _mm256_max_pd(v_GMIN, v_gm_raw);
        __m256d v_gds = _mm256_max_pd(v_GMIN, v_gds_raw);

        _mm256_storeu_pd(&tensor.ids[i], v_ids);
        _mm256_storeu_pd(&tensor.gm[i], v_gm);
        _mm256_storeu_pd(&tensor.gds[i], v_gds);
    }

    // --- Scalar Tail Loop ---
    for (; i < n; ++i) {
        int n_d = tensor.drains[i];
        double v_d = (n_d > 0 && n_d <= (int)voltages.size()) ? voltages[n_d - 1] : 0.0;
        int n_g = tensor.gates[i];
        double v_g = (n_g > 0 && n_g <= (int)voltages.size()) ? voltages[n_g - 1] : 0.0;
        int n_s = tensor.sources[i];
        double v_s = (n_s > 0 && n_s <= (int)voltages.size()) ? voltages[n_s - 1] : 0.0;

        double Kp = tensor.Kp[i];
        double W = tensor.W[i];
        double L = tensor.L[i];
        double Vth = tensor.Vth[i];
        double lam = tensor.lambda[i];

        double vgs = v_g - v_s;
        double vds = v_d - v_s;
        tensor.vgs[i] = vgs;
        tensor.vds[i] = vds;

        double beta = Kp * (W / L);
        double vov = vgs - Vth;

        double ids_raw = 0.5 * beta * vov * vov * (1.0 + lam * vds);
        double gm_raw = beta * vov * (1.0 + lam * vds);
        double gds_raw = 0.5 * beta * vov * vov * lam;

        tensor.ids[i] = std::max(0.0, ids_raw);
        tensor.gm[i] = std::max(1e-12, gm_raw);
        tensor.gds[i] = std::max(1e-12, gds_raw);
    }
}

#endif // __AVX2__
