// AUTO-GENERATED by Physics Compiler — DO NOT EDIT
// Model: MosfetLevel1
// Layout Hash: dcdd24f68522c42d
// Description: Level 1 MOSFET - Shichman-Hodges model with region-based evaluation

// SoA Buffer for MosfetLevel1
struct MosfetLevel1Data {
    node_d: array<i32>,
    node_g: array<i32>,
    node_s: array<i32>,
    node_b: array<i32>,
    Kp: array<f32>,
    W: array<f32>,
    L: array<f32>,
    Vt0: array<f32>,
    lambda_: array<f32>,
    GMIN: array<f32>,
    ids: array<f32>,
    gm: array<f32>,
    gds: array<f32>,
};

// Specialization constants
override WORKGROUP_SIZE: u32 = 64u;

@group(0) @binding(0) var<storage, read_write> devices: MosfetLevel1Data;
@group(0) @binding(1) var<storage, read> voltages: array<f32>;
@group(0) @binding(2) var<uniform> num_devices: u32;

@compute @workgroup_size(WORKGROUP_SIZE)
fn batch_mosfetlevel1_physics(@builtin(global_invocation_id) gid: vec3<u32>) {
    let i = gid.x;
    if (i >= num_devices) { return; }

    let n_d = devices.node_d[i];
    let v_d: f32 = select(0.0, voltages[n_d - 1], n_d > 0);
    let n_g = devices.node_g[i];
    let v_g: f32 = select(0.0, voltages[n_g - 1], n_g > 0);
    let n_s = devices.node_s[i];
    let v_s: f32 = select(0.0, voltages[n_s - 1], n_s > 0);
    let n_b = devices.node_b[i];
    let v_b: f32 = select(0.0, voltages[n_b - 1], n_b > 0);

    let Kp: f32 = devices.Kp[i];
    let W: f32 = devices.W[i];
    let L: f32 = devices.L[i];
    let Vt0: f32 = devices.Vt0[i];
    let lambda_: f32 = devices.lambda_[i];
    let GMIN: f32 = devices.GMIN[i];

    let vgs: f32 = (v_g - v_s);
    let vds: f32 = (v_d - v_s);
    let beta: f32 = ((W / L) * Kp);
    let vov: f32 = (vgs - Vt0);
    let ids_cutoff: f32 = 0.0;
    let gm_cutoff: f32 = 0.0;
    let gds_cutoff: f32 = GMIN;
    let ids_linear: f32 = ((((vds * vov) - ((f32(0.5) * vds) * vds)) * beta) * ((lambda_ * vds) + 1.0));
    let gm_linear: f32 = ((beta * vds) * ((lambda_ * vds) + 1.0));
    let gds_linear: f32 = (((((vds * vov) - ((f32(0.5) * vds) * vds)) * beta) * lambda_) + (((vov - vds) * beta) * ((lambda_ * vds) + 1.0)));
    let ids_sat: f32 = ((((f32(0.5) * beta) * vov) * vov) * ((lambda_ * vds) + 1.0));
    let gm_sat: f32 = ((beta * vov) * ((lambda_ * vds) + 1.0));
    let gds_sat: f32 = ((((f32(0.5) * beta) * vov) * vov) * lambda_);
    let in_cutoff: f32 = vov;
    let in_linear: f32 = vds;
    devices.ids[i] = max(0.0, ids_sat);
    let ids: f32 = devices.ids[i];
    devices.gm[i] = max(GMIN, gm_sat);
    let gm: f32 = devices.gm[i];
    devices.gds[i] = max(GMIN, gds_sat);
    let gds: f32 = devices.gds[i];
}
