// AUTO-GENERATED by Physics Compiler — DO NOT EDIT
// Model: Diode
// Layout Hash: 5ecfcf18bdcf0ede
// Description: PN Junction Diode - Shockley equation with linear continuation

// SoA Buffer for Diode
struct DiodeData {
    node_a: array<i32>,
    node_c: array<i32>,
    Is: array<f32>,
    N: array<f32>,
    Vt: array<f32>,
    Rs: array<f32>,
    GMIN: array<f32>,
    v_d: array<f32>,
    i_d: array<f32>,
    g_d: array<f32>,
};

// Specialization constants
override WORKGROUP_SIZE: u32 = 64u;

@group(0) @binding(0) var<storage, read_write> devices: DiodeData;
@group(0) @binding(1) var<storage, read> voltages: array<f32>;
@group(0) @binding(2) var<uniform> num_devices: u32;

@compute @workgroup_size(WORKGROUP_SIZE)
fn batch_diode_physics(@builtin(global_invocation_id) gid: vec3<u32>) {
    let i = gid.x;
    if (i >= num_devices) { return; }

    let n_a = devices.node_a[i];
    let v_a: f32 = select(0.0, voltages[n_a - 1], n_a > 0);
    let n_c = devices.node_c[i];
    let v_c: f32 = select(0.0, voltages[n_c - 1], n_c > 0);

    let Is: f32 = devices.Is[i];
    let N: f32 = devices.N[i];
    let Vt: f32 = devices.Vt[i];
    let Rs: f32 = devices.Rs[i];
    let GMIN: f32 = devices.GMIN[i];

    devices.v_d[i] = (v_a - v_c);
    let v_d: f32 = devices.v_d[i];
    let n_vt: f32 = (N * Vt);
    let arg: f32 = (v_d / n_vt);
    let arg_clamped: f32 = min(arg, 30.0);
    let exp_val: f32 = exp(arg_clamped);
    let i_base: f32 = ((exp_val - 1.0) * Is);
    let g_base: f32 = ((Is / n_vt) * exp_val);
    let delta: f32 = max(0.0, (v_d - (30.0 * n_vt)));
    devices.i_d[i] = ((delta * g_base) + i_base);
    let i_d: f32 = devices.i_d[i];
    devices.g_d[i] = max(GMIN, g_base);
    let g_d: f32 = devices.g_d[i];
}
